const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "Byte;;;eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiK0tvSERWTmZlRUtWYmVZZDBMQW5VajdkaHo1Z29qbjRJcysyNEN4WUhIcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYWdrZ0JXanN1SjRTbWhJa1hRcEpTLzBlV1ljcnk5Z096T0JxTEpQaUpYYz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJnRjcwWFY0RWlQRTRONE9JSVZ6L3VwNjJiVmRjbTh5d3BLZVg2dVdsOGtzPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJFSXdkUE8yNklUYUZtSlZkQzJ5UWdteGR3aXZKWlpreDVRQlErL0RaVnlRPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNJSXgwWXZlSmZMQ0hza3o1bUloNmV4UC9yUlpXZThZNmc1RzJuMDI5bmc9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjY5UkpNSEpoNUdVdmJBS2pkNHdRbkVST0x2TUxHdTVqOU9yMzJ4SW5pRG89In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaUF2WkwxcWQwYnMyOWYvcERsN1U0alJNOTZ3WVovMTBnQzcrNFpMVzdFbz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicDArczNnZHlRNFhMZytSektxRHZCR0JSWWI1Ky9XNFpKWVBraEk2bTdBOD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImdsSnd0encyVi94emJKaWF6NVJqSis5Rlh5NDZPaDMxaUt2aXJHRXhacHh5VmwwSzN1blN2aW4vaWE4dXVKZUE1OHpMNlNsMldEcTJ2by9tMmliY2l3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTA2LCJhZHZTZWNyZXRLZXkiOiJQMkYzZVlHQ1BpOWdMUmVHSGRTU21MeFlxNE5DL2NhMkJOYTNYd3NsNGI4PSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjIyODk3Mzk5ODA2QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkM0OEQ0MEIxODI0QzAyRDRFNjFDNUNBRUZDNDVDRUY3In0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3MzU3NDcwMDB9LHsia2V5Ijp7InJlbW90ZUppZCI6IjIyODk3Mzk5ODA2QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkM3RjdCNEU1RjdEQUVDNUUwRTMyNkNGODg5MEYzRjRCIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3MzU3NDcwMDZ9XSwibmV4dFByZUtleUlkIjozMiwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMyLCJhY2NvdW50U3luY0NvdW50ZXIiOjEsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6IldqVnFZM0dsUklHckZPRWhqdi03aXciLCJwaG9uZUlkIjoiZjk1ZGQzYmMtZTNjMC00MGE0LWIwM2ItZmE2NGIwNWJjMDI2IiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkREQmRkeFJNUFRpU0hITGs0aGxITGxGdUpldz0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIwdzBQb0h6UU1PRnBrZExmYXFPV1dzamk0ZE09In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiVFNTVzkxRzMiLCJtZSI6eyJpZCI6IjIyODk3Mzk5ODA2OjMwQHMud2hhdHNhcHAubmV0IiwibmFtZSI6IvCfpJ7wn4+94ZOA4aqjXHLwnZKN8J2ShvCdkpDwnZKR8J2SgvCdkpPwnZKF8J2SgvCdkpThqqNccuGTglxy8J+NgCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDS2lVdWJRQkVLVEwxYnNHR0FjZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiY3hHY25IdkNRcTNubVpxM20xSEJUbHlrLy9lQy9iRkRDaGpNcFdTc2VpYz0iLCJhY2NvdW50U2lnbmF0dXJlIjoiRFlBQ2RoTmRSMzJRbm5PVFFtcUZKSkJ5MFZMRWNmMHh4ZkZEa1l2Q2pORDRvNnMwSnNsV1pEY3NYKzdWTWJwZFdIaDcvejhtSzdQVlVtVzI2Z3MwRHc9PSIsImRldmljZVNpZ25hdHVyZSI6Im1lakRDWWFiWGp0ZUx3K29raFlpWit6WkdUWEo3dWl1UTI5bFJzK0VCVGZLZTZoSGJsUzNmTU9nSFdSZ1MrczFYOWlTSzB1bXYveEJpYnpNcWtSamdnPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjI4OTczOTk4MDY6MzBAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCWE1Sbkp4N3drS3Q1NW1hdDV0UndVNWNwUC8zZ3YyeFF3b1l6S1ZrckhvbiJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTczNTc0Njk5MywibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFBMmwifQ==",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "pubic",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "22897399806",
  "OWNER_NAME": process.env.OWNER_NAME || "Leopardas♌",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'falsr',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
